### PR TITLE
Initial concept of Privileges

### PR DESCRIPTION
**Pull request by someknave**
I have included the privilege list, which includes the image link path and the rules text. (currently all rules text is for privilege I(1).)
I have also included  1 line as an example for how this could be included in the module definitions.
I am thinking of coding some privileges with a 2 and some with a 1. If any of the 3 modules has a 1 it is included. if all 3 have a 2 then it is included. this will allow me to code things like the privilege I(11)  (not on for 9.I) and II(4) in for all residents games.

does this seem like a good way to do this?

### CODE REVIEW

**Comment by OsnaFonz** [comment]
Maybe we include the exceptions-list also into this def. like:
..., allow:{"2.I",...}, disallow:{"residents"}

**Comment by someknave** [comment]
I don't think that's necessary, as it will be included in the module defs. That way it uses the exact same techniques as we are already using.

**Comment by someknave** [comment]
Made some more updates, still working on compiling the privilege list.

**Comment by OsnaFonz** [comment]
hi someknave, can you take a look at my approach to integrate the privileges?
i am not so happy to include so much rulestext into the defs. what do you think?
https://github.com/504rules/504rules.github.io/compare/master...OsnaFonz:include-privileges
(the position of the cards is not final and the query for residents is currently missing, the card rules can be added in the template file)

**Comment by someknave** [comment]
Yeah, as long as the job gets done I don't mind how. the rules can probably come from templating.I prefer for privileges to work the same way as game parts but that is an approach preference.

The name of each privilege should be in the form II-10 as that is closer to the form from the rulebook.

Also I don't think that the privileges by default should appear in the rules anyway. a list of the privileges included (just names) would suffice in the game prep section.

The full card image with rules explanation should be an appendix after the rules, in the full rules version.

**Comment by OsnaFonz** [comment]
the idea of an appendix after the rules is fine. also i will prepare images for the game parts and some kind of menu where we could put the extended privileges switch (and the language switch, extended view for the game parts, randomizer, ...)

**Comment by OsnaFonz** [comment]
that's my work for today. the rules for lv2 and lv3 are following
https://github.com/OsnaFonz/504rules.github.io/tree/privileges-edit

lv2&3 added :-)
https://github.com/OsnaFonz/504rules.github.io/tree/edit-privileges-rules-lv2

http://osnafonz.github.io/504rules.github.io

**Comment by someknave** [comment]
Are you ready to merge yours with the base? if so I will delete my branch, it is irrelevant now.

**Pull request closed without merging**
