### PR TITLE
My attempt at creating tags to switch between player/president.

### PR DESCRIPTION
**Pull request by someknave**
As discussed in issue #15, the current rules don't distinguish between whether a player is doing something or a company. I have created the following tags to try to remedy this. (the document will still need to be updated if people feel like this is the way to go forward.)
entity is either player/company and agent is either player/president. I felt that in the case of stock companies these shouldn't be mixed up. The president makes decisions and moves on the board, the company owns things, loses things, and gains things.
I also feel that the word "his" should be replaced by "the company's" and "its" depending on context. (If company isn't in the sentence yet "the company's" should be used otherwise "its" should suffice.)

I don't really like my solution, I feel that there should be a more elegant way of doing this with a single function call, but all the methods I tried didn't seem to work. If anyone has any suggestions let me know.

If people are happy I will implement this through the rules.

### CODE REVIEW

**Comment by Arachnid** [comment]
This does seem like the best of bad options for handling this. Thanks for putting it together.

For the script, it'd be good to see "isCompanyGame" functions or similar, instead of putting the logic for deciding this inline. Other than that, it looks good to me.

**Comment by OsnaFonz** [comment]
is it possible to take the text out of the functions in a separate Object, so that is easier for the language support?

**Comment by Arachnid** [comment]
Did you give up on this?

**Comment by someknave** [comment]
no, I'm going to try something different, I'm going to have to remove all of the commits before I try again as this is messy.

**Pull request closed without merging**
