### PR TITLE
added resident info and *~ to .gitignore

### PR DESCRIPTION
**Pull request by bithalver**
Added 2 things:
- Playing with(out) residents
- *~ to .gitignore

### CODE REVIEW

**Comment by Arachnid** [comment]
I'm a little concerned the line about residents won't fit in the (currently fixed-height) boxes up top. How does it look on the printout?

I'm also wondering if it would make more sense to have a meeple or crossed-through-meeple icon rather than text. What do you think?

**Comment by bithalver** [comment]
Hmmm, the line I added will surely fit (the next box with starting money will have at least 2 lines anyhow), BUT a (normal or crossed-over) meeple is a good idea. Why not !

**Comment by Arachnid** [comment]
With share order, though, this box will now have 3 lines rather than two!

**Comment by bithalver** [comment]
OK, then let's move on to a single meeple icon.

**Comment by bithalver** [comment]
Now I added two icons and 2 lines to have a normal or crossed over meeple on the title line.

**Comment by Arachnid** [comment]
LGTM, except for the sizing in %. Could you make it a stylesheet rule, and size it in px, like everything else?

**Comment by bithalver** [comment]
Ooops.
- I have no connection to stylesheets, sorry.
- I just copied and modified the code for another images, their size are also specified by percent ...

**Comment by Arachnid** [comment]
No worries, I'll tweak it. Thanks for the submission!

**Pull request merged**
