### PR TITLE
Final View changes

### PR DESCRIPTION
**Pull request by OsnaFonz**
New Display View (Print View is still the same)
Fixed Issues #39 and #35 
Include Map Icons

### CODE REVIEW

**Comment by Arachnid** [comment]
Does this obsolete your earlier PR, or build on it?

**Comment by OsnaFonz** [comment]
I closed the older requests. they are now included in this one.

**Comment by OsnaFonz** [comment]
You can take a look at it here:
http://osnafonz.github.io/504rules.github.io/

**Comment by Arachnid** [comment]
I'm really sorry this took me so long. The changes look great!

**Pull request merged**
