### PR TITLE
Added map images

### PR DESCRIPTION
**Pull request by tjhighley**
Added map images for use as icons in header.  (Not actually added to the header yet.)

### CODE REVIEW

**Comment by Arachnid** [comment]
Where are you figuring on using these? They seem too large for the header, but would work for a 'full rules' sheet.

**Comment by tjhighley** [comment]
I figured they would be resized for the header.  Not large enough to actually do the setup, but large enough that someone could say, "Oh right - that map."

**Comment by Arachnid** [comment]
I think for any images that size we'll need simplified icons; shrinking these down will result in illegible text.

**Comment by tjhighley** [comment]
I wouldn't expect the text to be legible.  Just a small image to remind someone of the shape of Map 1, 2, 3, etc.

**Comment by tjhighley** [comment]
You can close this.  No longer relevant.

**Pull request closed without merging**
